# This is a basic workflow to help you get started with Actions

name: BuildOutput

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
         # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.10 # optional
         # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pipenv
         # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
     
      - name: Install dependencies
        run: |
          pipenv lock
          pipenv sync
      
      - name: Pelican Build
        run: pipenv run pelican --ignore-cache -s publishconf.py content
