name: Build Blog Contents.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
         # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: '3.10' # optional
         # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pipenv
         # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
     
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv lock
          pipenv sync
        
      - name: Clone blue-penguin theme.
        run: git clone https://github.com/jody-frankowski/blue-penguin.git ./blue-penguin
          
      - name: Install blue-penguin
        run: pipenv run pelican-themes --install ./blue-penguin
      
      - name: Pelican Build
        run: pipenv run pelican --ignore-cache -s publishconf.py content
        
      - name: Upload output.
        uses: actions/upload-artifact@v3.1.0
        with:
    # Artifact name
          name: BlogOutput
    # A file, directory or wildcard pattern that describes what to upload
          path: ./output/*
    # The desired behavior if no files are found using the provided path.
          if-no-files-found: fail
    # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 10
